swagger: "2.0"
info:
  title: Divider Service
  description: An example illustrating error handling in goa. See docs/ErrorHandling.md.
  version: ""
host: localhost:8080
paths:
  /div/{a}/{b}:
    get:
      tags:
      - divider
      summary: divide divider
      operationId: divider#divide
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: number
        format: double
      - name: b
        in: path
        description: Right operand
        required: true
        type: number
        format: double
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            type: number
            format: double
        "400":
          description: Bad Request response.
          schema:
            schema: ""
            $ref: '#/definitions/DivideDivByZeroResponseBody'
        "504":
          description: Gateway Timeout response.
          schema:
            schema: ""
            $ref: '#/definitions/DivideTimeoutResponseBody'
      schemes:
      - http
  /idiv/{a}/{b}:
    get:
      tags:
      - divider
      summary: integer_divide divider
      operationId: divider#integer_divide
      parameters:
      - name: a
        in: path
        description: Left operand
        required: true
        type: integer
      - name: b
        in: path
        description: Right operand
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            schema: ""
            type: integer
            format: int64
        "400":
          description: Bad Request response.
          schema:
            schema: ""
            $ref: '#/definitions/IntegerDivideDivByZeroResponseBody'
        "417":
          description: Expectation Failed response.
          schema:
            schema: ""
            $ref: '#/definitions/IntegerDivideHasRemainderResponseBody'
        "504":
          description: Gateway Timeout response.
          schema:
            schema: ""
            $ref: '#/definitions/IntegerDivideTimeoutResponseBody'
      schemes:
      - http
definitions:
  DivideDivByZeroResponseBody:
    schema: ""
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      id:
        schema: ""
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        schema: ""
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        schema: ""
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        schema: ""
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        schema: ""
        type: boolean
        description: Is the error a timeout?
        example: false
    description: divizion by zero (default view)
    example:
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
  DivideTimeoutResponseBody:
    schema: ""
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      id:
        schema: ""
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        schema: ""
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        schema: ""
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        schema: ""
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        schema: ""
        type: boolean
        description: Is the error a timeout?
        example: true
    description: operation timed out, retry later. (default view)
    example:
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
  IntegerDivideDivByZeroResponseBody:
    schema: ""
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      id:
        schema: ""
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        schema: ""
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        schema: ""
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        schema: ""
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        schema: ""
        type: boolean
        description: Is the error a timeout?
        example: true
    description: divizion by zero (default view)
    example:
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
  IntegerDivideHasRemainderResponseBody:
    schema: ""
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      id:
        schema: ""
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        schema: ""
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        schema: ""
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        schema: ""
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        schema: ""
        type: boolean
        description: Is the error a timeout?
        example: false
    description: integer division has remainder (default view)
    example:
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
  IntegerDivideTimeoutResponseBody:
    schema: ""
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      id:
        schema: ""
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        schema: ""
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        schema: ""
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        schema: ""
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        schema: ""
        type: boolean
        description: Is the error a timeout?
        example: true
    description: operation timed out, retry later. (default view)
    example:
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
